const pool = require('../db/pool');

const getAllCollections = async (req, res) => {
  try {
    const { parent_collection } = req.query;
    if (parent_collection === "null") {
      const result = await pool.query('SELECT * FROM item_collection WHERE parent_collection IS NULL');
      return res.json(result.rows);
    }
    else if (parent_collection) {
      const result = await pool.query(
        'SELECT * FROM item_collection WHERE parent_collection = $1',
        [parent_collection]
      );
      return res.json(result.rows);
    }
    const result = await pool.query('SELECT * FROM item_collection');
    res.json(result.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

// Returns all collections that are valid move destinations for a given folder.
// Excludes the folder itself and all its descendants to prevent cycles. (generated by Claude)
const getRelocateOptions = async (req, res) => {
  try {
    const { type, id } = req.params;
    let result;
    if (type === "folder") {
      result = await pool.query(
        `WITH RECURSIVE excluded AS (
          SELECT id FROM item_collection WHERE id = $1
          UNION ALL
          SELECT c.id FROM item_collection c
            JOIN excluded e ON c.parent_collection = e.id
        )
        SELECT * FROM item_collection
          WHERE id NOT IN (SELECT id FROM excluded)
          ORDER BY title`,
        [id]
      );
    }
    else {
      result = await pool.query(
        `SELECT * FROM item_collection ORDER BY title`
      );
    }
    res.json(result.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
}

const getCollectionById = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      'SELECT * FROM item_collection WHERE id = $1',
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Collection not found' });
    }

    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

const createCollection = async (req, res) => {
  try {
    const { title, parent_collection } = req.body;
    const result = await pool.query(
      'INSERT INTO item_collection (title, parent_collection) VALUES ($1, $2) RETURNING *',
      [title, parent_collection || null]
    );
    res.status(201).json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

// Returns the chain from root to the given folder (inclusive), ordered root→leaf
// Used by the frontend breadcrumb. (generated by Claude)
const getCollectionAncestors = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      `WITH RECURSIVE ancestors AS (
         SELECT id, title, parent_collection, 0 AS depth
           FROM item_collection
          WHERE id = $1
         UNION ALL
         SELECT c.id, c.title, c.parent_collection, a.depth + 1
           FROM item_collection c
           JOIN ancestors a ON c.id = a.parent_collection
       )
       SELECT id, title FROM ancestors ORDER BY depth DESC`,
      [id]
    );
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Collection not found' });
    }
    res.json(result.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

const updateCollection = async (req, res) => {
  try {
    const { id } = req.params;
    const { title } = req.body;
    const result = await pool.query(
      'UPDATE item_collection SET title = $1 WHERE id = $2 RETURNING *',
      [title, id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Collection not found' });
    }

    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

const deleteCollection = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      'DELETE FROM item_collection WHERE id = $1 RETURNING *',
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Collection not found' });
    }

    res.json({ message: 'Collection deleted' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

const moveFolder = async (req, res) => {
  try {
    const { id, dest_id } = req.params;
    const dest = dest_id === 'null' ? null : dest_id;
    const result = await pool.query(
      'UPDATE item_collection SET parent_collection = $1 WHERE id = $2 RETURNING *',
      [dest, id]
    )
    if (!result.rows[0]) return res.status(404).json({ error: 'Collection not found' });
    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
}

module.exports = {
  getAllCollections,
  getCollectionById,
  getCollectionAncestors,
  getRelocateOptions,
  createCollection,
  updateCollection,
  deleteCollection,
  moveFolder,
};