const pool = require('../db/pool');
const bcrypt = require('bcrypt');

const getAllUsers = async (req, res) => {
  try {
    const result = await pool.query('SELECT id, name, email, phone, avatar, role, birthday FROM users');
    res.json(result.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

const getUserById = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      'SELECT id, name, email, phone, avatar, role FROM users WHERE id = $1',
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'User not found' });
    }

    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

const createUser = async (req, res) => {
  try {
    const { name, email, password, phone, role, birthday } = req.body;
    // Avatar comes from multer file upload (generated by Claude)
    const avatar = req.file ? `/uploads/${req.file.filename}` : null;
    const hashedPassword = await bcrypt.hash(password, 10);
    const result = await pool.query(
      'INSERT INTO users (name, email, password, phone, avatar, role, birthday) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *',
      [name, email || null, hashedPassword, phone || null, avatar, role, birthday || null]
    );
    res.status(201).json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

const updateUser = async (req, res) => {
  try {
    const { id } = req.params;
    const { name, email, password, phone, role, birthday } = req.body;
    // Use newly uploaded file if provided, otherwise keep the existing avatar URL sent from the frontend (generated by Claude)
    const avatar = req.file ? `/uploads/${req.file.filename}` : (req.body.avatar || null);

    let query, values;
    if (password) {
      // Only re-hash and update password when a new one is provided
      const hashedPassword = await bcrypt.hash(password, 10);
      query = 'UPDATE users SET name = $1, email = $2, password = $3, phone = $4, avatar = $5, role = $6, birthday = $7 WHERE id = $8 RETURNING *';
      values = [name, email || null, hashedPassword, phone || null, avatar, role, birthday || null, id];
    } else {
      // Leave password column untouched
      query = 'UPDATE users SET name = $1, email = $2, phone = $3, avatar = $4, role = $5, birthday = $6 WHERE id = $7 RETURNING *';
      values = [name, email || null, phone || null, avatar, role, birthday || null, id];
    }

    const result = await pool.query(query, values);

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'User not found' });
    }

    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

const deleteUser = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      'DELETE FROM users WHERE id = $1 RETURNING *',
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'User not found' });
    }

    res.json({ message: 'User deleted' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
};

module.exports = {
  getAllUsers,
  getUserById,
  createUser,
  updateUser,
  deleteUser,
};