const express = require('express');
const router = express.Router();
const usersController = require('../controllers/usersController');
const authenticate = require('../middleware/authenticate');
const { adminOnly, selfOrAdmin } = require('../middleware/authorize');
const upload = require('../middleware/upload'); // generated by Claude — avatar upload

router.get('/', authenticate, usersController.getAllUsers);
router.get('/:id', authenticate, usersController.getUserById);
router.post('/', authenticate, adminOnly, upload.single('avatar'), usersController.createUser);
router.put('/:id', authenticate, selfOrAdmin, upload.single('avatar'), usersController.updateUser);
router.delete('/:id', authenticate, selfOrAdmin, usersController.deleteUser);

module.exports = router;